[phases.setup]
nixPkgs = ['php', 'composer', 'nodejs', 'npm']

[phases.install]
cmds = [
  "composer install",
  "npm install --production"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan optimize",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
